---
title: "STATAssignment_1"
author: "Zhongzhen Wang"
date: "2015年10月7日"
output: html_document
---

## Section 4.1.1

Exercise 1 (a)
```{r}
Fibonacci <- numeric(12)
Fibonacci[1] <- 2
Fibonacci[2] <- 2
for(i in 3:12) Fibonacci[i] <- Fibonacci[i-2] + Fibonacci[i-1]
print(Fibonacci)

```

Exercise 1 (b)
```{r}
Fibonacci[1] <- 3
Fibonacci[2] <- 2
for(i in 3:12) Fibonacci[i] <- Fibonacci[i-2] + Fibonacci[i-1]
print(Fibonacci)
```

Exercise 1 (c)
```{r}
Fibonacci[1] <- 2
Fibonacci[2] <- 3
for(i in 3:12) Fibonacci[i] <- Fibonacci[i-1] - Fibonacci[i-2]
print(Fibonacci)
```

Exercise 1 (d)
```{r}
Fibonacci[1] <- Fibonacci[2] <- Fibonacci[3] <- 1
for(i in 4:12) Fibonacci[i] <- Fibonacci[i-1] + Fibonacci[i-2] + Fibonacci[i-3]
print(Fibonacci)
```

Exercise 2 (a)
```{r}
Fibonacci <- numeric(30)
fn <- numeric(30)
Fibonacci[1] <- 1
Fibonacci[2] <- 1
for(i in 3:30) Fibonacci[i] <- Fibonacci[i-1] + Fibonacci[i-2]
for(i in 2:30) fn[i] <- Fibonacci[i]/Fibonacci[i-1]
print(fn)
```

Exercise 2 (b)
```{r}
(sqrt(5)+1)/2
```

Exercise 3 (a)
```{r}
answer <- 0
for(j in 1:5) answer <- answer + j
print(answer)
# sum of integers from 1 to 5
```

Exercise 3 (b)
```{r}
answer <- NULL
for(j in 1:5) answer <- c(answer, j)
print(answer)
# a column containing integers 1 to 5
```

Exercise 3 (c)
```{r}
answer <- 0
for(j in 1:5) answer <- c(answer,j)
print(answer)
# a column containing integers 0 to 5
```

Exercise 3 (d)
```{r}
answer <- 1
for(j in 1:5) answer <- answer*j
print(answer)
# multiplication of integers from 1 to 5
```

Exercise 3 (e)
```{r}
answer <- 3
for(j in 1:15) answer <- c(answer, (7*answer[j]) %% 31)
print(answer)
# 3*7^n in a group of 31, for integer n in 1 to 15
```

## Section 4.1.2

Exercise 4
```{r}
I <- function(P, n) {
if(n <= 3) {
I <- P*((1+0.04)^n-1)
}
else{
I <- P*((1+0.05)^n-1)
}
}
print(I(1000, 3))
print(I(1000, 5))
```

Exercise 5
```{r}
R <- function(n, P, open){
if(open == TRUE) {
P*(0.005)/(1-(1+0.005)^(-0.005))
}
  else{
P*(0.004)/(1-(1+0.004)^(-0.004))
  }
}
print(R(5, 100, TRUE))
print(R(5, 100, FALSE))
```

## Section 4.1.3

Exercise 1
```{r}
Fib1 <- 1
Fib2 <- 1
Fibonacci <- c(Fib1, Fib2)
while(Fib1<300){
Fibonacci <- c(Fibonacci, Fib2)
Fib2 <- Fib1 + Fib2
Fib1 <- max(Fibonacci)
}
print(Fibonacci)
```

Exercise 2
```{r}
Fibonacci <- c(1,1)
while(max(Fibonacci) < 300) {
Fibonacci <- c(Fibonacci, Fibonacci[length(Fibonacci)] + Fibonacci[length(Fibonacci)-1])
}
print(Fibonacci)
```

Exercise 4
```{r}
i <- 1
ii <- 0.006
while(abs(i-ii) > 10^(-6)) {
i <- ii
ii <- (1-(1+i)^(-20))/19
}
print(i)

# If I set i=0.006, the while loop fails to operate, which gives the output 0.006.

i <- 0.006
ii <- 0.006
while(abs(i-ii) > 10^(-6)) {
i <- ii
ii <- (1-(1+i)^(-20))/19
}
print(i)
```

Exercise 5
```{r}
i <- 0
ii <- 0.006
count <- 0
while(abs(i-ii) > 10^(-6)) {
i <- ii
ii <- (1-(1+i)^(-20))/19
count <- count +1
}
print(count)
```

## Section 4.1.5

Exercise 2 (a)
```{r}
Eratosthenes <- function(n) {
if (n >= 2) { 
sieve <- seq(2, n) 
primes <- c()
while (length(sieve) > 0) { 
p <- sieve[1]
primes <- c(primes, p)
sieve <- sieve[(sieve %% p) != 0] 
}
return(primes) 
} else { 
stop("Input value of n should be at least 2.") 
}
}
Eratosthenes(30)

# I have understood how it works.
```

Exercise 2 (b)
```{r}

```

Exercise 2 (c)
```{r}
Eratosthenes <- function(n) {
if (n >= 2) { 
sieve <- seq(2, n) 
primes <- c()
repeat{
p <- sieve[1]
if (length(sieve) == 0) break
primes <- c(primes, p)
sieve <- sieve[(sieve %% p) != 0] 
}
return(primes)
}
}
print(Eratosthenes(30))
```