---
title: "Assignment 2"
author: "Zhongzhen Wang"
date: "2015年10月12日"
output: html_document
---


4.2.1 
Exercise 2 (a) & (b)
```{r}
compound.interest <- function(P, ir, n) {
P*(1+ir)^n - P
}
print(compound.interest(1000, 0.01, 30))
```

Exercise 3
```{r}
bisect <- function(fun, x1, x2){
tol <- 10^(-6)
while(abs(x1-x2) > tol){
  x3 <- (x1 + x2)/2
  if(fun(x1)*fun(x3) > 0) {
  x1 <- x3
  }
  else{
    x2 <- x3
  }
  print(x3)
}
}
```

4.4.1
Exercise 1
```{r}
mergesort <- function(x, decreasing = TRUE){
  if(decreasing == TRUE){
    len <- length(x)
    if(len < 2){
      result <- x
    }
    else{
      y <- x[1 : (len/2)]
      z <- x[((len/2)+1) : len]
      y <- mergesort(y , decreasing = TRUE)
      z <- mergesort(z , decreasing = TRUE)
      result <- c()
      while(min(length(y) , length(z)) > 0){
        if(y[1] > z[1]){
          result <- c(result , y[1])
          y <- y[-1]
        }
        else{
          result <- c(result , z[1])
          z <- z[-1]
        }
      }
      if(length(y) > 0){
        result <- c(result , y)
      }
      else{
        result <- c(result , z)
      }
      return(result)
    }
  }
  else{
    len <- length(x)
    if(len < 2){
      result <- x
    }
    else{
      y <- x[1 : (len/2)]
      z <- x[((len/2)+1) : len]
      y <- mergesort(y , decreasing = FALSE)
      z <- mergesort(z , decreasing = FALSE)
      result <- c()
      while(min(length(y) , length(z)) > 0){
        if(y[1] < z[1]){
          result <- c(result , y[1])
          y <- y[-1]
        }
        else{
          result <- c(result , z[1])
          z <- z[-1]
        }
      }
      if(length(y) > 0){
        result <- c(result , y)
      }
      else{
        result <- c(result , z)
      }
    }
    return(result)
  }
}
```

Exercise 2(a)
```{r}
newton <- function(f , g, tol=1E-12 , x0 = 1, y0 = 1, N = 50) {
        h <- 0.001
        i <- 1 
        x1 <- x0
        y1 <- y0
        p <- numeric(N)
        q <- numeric(N)
        while (i <= N){
                df.dx <- (f(x0+h,y0) - f(x0,y0))/h
                dg.dx <- (g(x0+h,y0) - g(x0,y0))/h
                df.dy <- (f(x0,y0+h) - f(x0,y0))/h
                dg.dy <- (g(x0,y0+h) - g(x0,y0))/h
                dist <- df.dx*dg.dy - df.dy*dg.dx
                x1 <- x0 - (dg.dy*f(x0,y0)-df.dy*g(x0,y0))/dist
                y1 <- y0 - (df.dx*g(x0,y0)-dg.dx*f(x0,y0))/dist
                p[i] <- x1
                q[i] <- y1
                i <- i + 1
                if (abs(x1-x0) < tol && abs(y1-y0) < tol) break
                x0 <- x1
                yo <- y1
        }
        return(p[1:(i-1)] , q[1:(i-1)])
}
f <- function(x,y){x + y <- 0}
g <- function(x,y){x^2 + 2*y^2 - 2 <- 0}
```

Exercise 2(b)
```{r}
sqrt(2/3)
-sqrt(2/3)
```

Chapter Question 1
```{r}
directpoly <- function(x,co){
  n <- length(co)
  poly <- 0
  for(i in 1:n){
    poly <- poly + co[i]*x^(n-i)
  }
  return(poly)
}
```

Question 2
```{r}
hornerpoly <- function(x,co){
  n <- length(co)
  a <- matrix(0, length(x), n)
  for(i in (n-1):1){
    a[,n] <- co[1]
    a[,i] <- a[,i+1]*x + co[n-i+1]
  }
  return(a[,1])
}
```

Question 3(a)
```{r}
system.time(directpoly(x=seq(-10, 10, length=5000000), + c(1, -2, 2, 3, 4, 6, 7))) 
system.time(hornerpoly(x=seq(-10, 10, length=5000000), + c(1, -2, 2, 3, 4, 6, 7))) 
```

Question 3(b)
```{r}
system.time(directpoly(x=seq(-10, 10, length=5000000), + c(2, 17, -1))) 
system.time(hornerpoly(x=seq(-10, 10, length=5000000), + c(2, 17, -1))) 
## When the number of coefficients is smaller, the time of operation of both methods are almost the same.
```